[tool.poetry]
name = "openbb-pyth2"
version = "1.0.2"
description = "Pyth Extension to fetch MarketCap"
authors = ["OpenBB <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_pyth2" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
mmprvd = "openbb_providers:pyth2_provider"